### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by SanderBilly** [SanderBilly/furima-33944#10]
## アプリのURL(Heroku)
https://
  
## Basic認証のユーザー名とパスワード
> ユーザー名：
> パスワード：
  
## 出品者用のメールアドレスとパスワード
> メールアドレス：00@mail
> パスワード　　：00mail
  
## 購入者用のメールアドレスとパスワード
> メールアドレス：11@mail
> パスワード　　：11mail
  
## 購入用カードの番号・期限・セキュリティコード
> カードの番号　　　：4242424242424242
> 期限　　　　　　　：3/23
> セキュリティコード：123

**Comment by mo1015** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！
**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/62644781/104831831-9539cd80-58cf-11eb-89e3-251cc1ab0fa0.png)
